### ISSUE TITLE
Webstorm 9 EAP issue

### ISSUE THREAD

**Issue by dylang** [nicoulaj/idea-markdown#172]
Trying out the [Webstorm 9 EAP](http://blog.jetbrains.com/webstorm/2014/08/webstorm-9-eap/), got this error:

```
com/intellij/openapi/fileEditor/impl/TrailingSpacesStripper
java.lang.NoClassDefFoundError: com/intellij/openapi/fileEditor/impl/TrailingSpacesStripper
    at net.nicoulaj.idea.markdown.lang.psi.impl.MarkdownFileImpl.getVirtualFile(MarkdownFileImpl.java:67)
    at com.intellij.psi.util.PsiUtilCore.getVirtualFile(PsiUtilCore.java:356)
    at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.isHighlightingAvailable(DaemonCodeAnalyzerImpl.java:450)
    at com.intellij.openapi.wm.impl.status.TogglePopupHintsPanel.b(TogglePopupHintsPanel.java:157)
    at com.intellij.openapi.wm.impl.status.TogglePopupHintsPanel.a(TogglePopupHintsPanel.java:125)
    at com.intellij.openapi.wm.impl.status.TogglePopupHintsPanel.updateStatus(TogglePopupHintsPanel.java:121)
    at com.intellij.openapi.wm.impl.status.TogglePopupHintsPanel.fileOpened(TogglePopupHintsPanel.java:66)
    at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
    at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
    at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
    at com.sun.proxy.$Proxy76.fileOpened(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$10$1.run(FileEditorManagerImpl.java:877)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13$1.run(FileEditorManagerImpl.java:968)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:635)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:605)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:501)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2077)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:479)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:974)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$300(ActionToolbarImpl.java:64)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$4.run(ActionToolbarImpl.java:1000)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:724)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:551)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: com.intellij.openapi.fileEditor.impl.TrailingSpacesStripper PluginClassLoader[net.nicoulaj.idea.markdown, 0.9.6]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 48 more



java.lang.NoClassDefFoundError: com/intellij/openapi/fileEditor/impl/TrailingSpacesStripper
    at net.nicoulaj.idea.markdown.lang.psi.impl.MarkdownFileImpl.getVirtualFile(MarkdownFileImpl.java:67)
    at com.intellij.ide.browsers.OpenInBrowserRequest.getVirtualFile(OpenInBrowserRequest.java:47)
    at org.jetbrains.builtInWebServer.BuiltInWebBrowserUrlProvider.canHandleElement(BuiltInWebBrowserUrlProvider.java:66)
    at com.intellij.ide.browsers.impl.WebBrowserServiceImpl.getProvider(WebBrowserServiceImpl.java:81)
    at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction.doUpdate(BaseOpenInBrowserAction.java:156)
    at com.intellij.ide.browsers.actions.BaseOpenInBrowserAction.update(BaseOpenInBrowserAction.java:77)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
    at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:187)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:138)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:163)
    at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:95)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.run(ActionToolbarImpl.java:928)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:654)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:635)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:605)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
    at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:501)
    at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2077)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:479)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:974)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$300(ActionToolbarImpl.java:64)
    at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$4.run(ActionToolbarImpl.java:1000)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:724)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:551)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

**Comment by Mike-Loffland** [comment]
#### Webstorm 9

To install this Markdown plugin via the Webstorm 9 interface, press the "Browse repositories..." button when you're on the Plugins dialog box. Then, search for Markdown and install.
