### ISSUE TITLE
IllegalArgumentException when switching between Text and Preview

### ISSUE THREAD

**Issue by nmaynes** [nicoulaj/idea-markdown#196]
Intellij 13.1.5 is throwing errors in the event log when switching back and forth between the Text and Preview panes. The error thrown is:

`Argument for @NotNull parameter 'target' of net/nicoulaj/idea/markdown/editor/MarkdownPathResolver.resolveRelativePath must not be null: Argument for @NotNull parameter 'target' of net/nicoulaj/idea/markdown/editor/MarkdownPathResolver.resolveRelativePath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'target' of net/nicoulaj/idea/markdown/editor/MarkdownPathResolver.resolveRelativePath must not be null
    at net.nicoulaj.idea.markdown.editor.MarkdownPathResolver.resolveRelativePath(MarkdownPathResolver.java)
    at net.nicoulaj.idea.markdown.editor.MarkdownEditorKit$MarkdownImageView.getImageURL(MarkdownEditorKit.java:138)
    at javax.swing.text.html.ImageView.loadImage(ImageView.java:691)
    at javax.swing.text.html.ImageView.refreshImage(ImageView.java:673)
    at javax.swing.text.html.ImageView.sync(ImageView.java:645)
    at javax.swing.text.html.ImageView.getPreferredSpan(ImageView.java:443)
    at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:732)
    at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
    at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:724)
    at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
    at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
    at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
    at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
    at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
    at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
    at javax.swing.text.BoxView.layout(BoxView.java:708)
    at javax.swing.text.BoxView.setSize(BoxView.java:397)
    at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1714)
    at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1660)
    at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1332)
    at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:790)
    at java.awt.Container.layout(Container.java:1503)
    at java.awt.Container.doLayout(Container.java:1492)
    at java.awt.Container.validateTree(Container.java:1688)
    at java.awt.Container.validate(Container.java:1623)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:691)
    at javax.swing.RepaintManager$2.run(RepaintManager.java:689)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:688)
    at com.intellij.ide.IdeRepaintManager.validateInvalidComponents(IdeRepaintManager.java:114)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1676)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).

**Comment by nmaynes** [comment]
Thanks for the update @nicoulaj and for building this plugin.
