### ISSUE TITLE
Webstorm 9 Error: org/objectweb/asm/tree/AbstractInsnNode

### ISSUE THREAD

**Issue by grbspltt** [nicoulaj/idea-markdown#210]
Webstorm 9 Error message: org/objectweb/asm/tree/AbstractInsnNode

Created a new project using Webstorm's AngularJS option. Ran npm install per instructions, and this error occurred.

**Comment by mnahkies** [comment]
I'm getting this error as well, on WebStorm 9.0.3

Full stack trace:

    org/objectweb/asm/tree/AbstractInsnNode
    java.lang.NoClassDefFoundError: org/objectweb/asm/tree/AbstractInsnNode
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
        at net.nicoulaj.idea.markdown.editor.MarkdownPreviewEditor$1.initialValue(MarkdownPreviewEditor.java:91)
        at net.nicoulaj.idea.markdown.editor.MarkdownPreviewEditor$1.initialValue(MarkdownPreviewEditor.java:89)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
        at java.lang.ThreadLocal.get(ThreadLocal.java:150)
        at net.nicoulaj.idea.markdown.editor.MarkdownPreviewEditor.selectNotify(MarkdownPreviewEditor.java:223)
        at com.intellij.openapi.fileEditor.impl.EditorComposite$4$1.run(EditorComposite.java:197)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
        at com.intellij.openapi.fileEditor.impl.EditorComposite$4.selectionChanged(EditorComposite.java:203)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:285)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
        at com.sun.proxy.$Proxy79.update(Unknown Source)
        at org.zmlx.hg4idea.HgVcs$2.selectionChanged(HgVcs.java:299)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:285)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
        at com.sun.proxy.$Proxy52.daemonCancelEventOccurred(Unknown Source)
        at com.intellij.codeInsight.daemon.impl.DaemonListeners.a(DaemonListeners.java:623)
        at com.intellij.codeInsight.daemon.impl.DaemonListeners.access$100(DaemonListeners.java:96)
        at com.intellij.codeInsight.daemon.impl.DaemonListeners$MyCommandListener.commandFinished(DaemonListeners.java:481)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:187)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:161)
        at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:54)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:130)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
        at com.intellij.openapi.fileEditor.impl.EditorComposite$4.selectionChanged(EditorComposite.java:203)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
        at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:315)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:302)
        at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:294)
        at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:287)
        at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
        at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
        at com.sun.proxy.$Proxy76.selectionChanged(Unknown Source)
        at com.intellij.openapi.fileEditor.impl.EditorComposite$5.run(EditorComposite.java:254)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13$1.run(FileEditorManagerImpl.java:988)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:648)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
        at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
        at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:471)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:64)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:985)
        at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:123)
        at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:981)
        at com.intellij.openapi.fileEditor.impl.EditorComposite.a(EditorComposite.java:249)
        at com.intellij.openapi.fileEditor.impl.EditorComposite.access$600(EditorComposite.java:63)
        at com.intellij.openapi.fileEditor.impl.EditorComposite$MyChangeListener.stateChanged(EditorComposite.java:419)
        at com.intellij.ui.JBTabsPaneImpl.a(JBTabsPaneImpl.java:102)
        at com.intellij.ui.JBTabsPaneImpl.access$100(JBTabsPaneImpl.java:37)
        at com.intellij.ui.JBTabsPaneImpl$2.selectionChanged(JBTabsPaneImpl.java:88)
        at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.java:921)
        at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:874)
        at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:838)
        at com.intellij.ui.tabs.impl.JBTabsImpl.select(JBTabsImpl.java:823)
        at com.intellij.ui.tabs.impl.TabLabel$1.mousePressed(TabLabel.java:89)
        at java.awt.Component.processMouseEvent(Component.java:6513)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:708)
        at java.awt.EventQueue$4.run(EventQueue.java:706)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
    Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.AbstractInsnNode PluginClassLoader[net.nicoulaj.idea.markdown, 0.9.7]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 117 more



    java.lang.NoClassDefFoundError: org/objectweb/asm/tree/AbstractInsnNode
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator$1.initialValue(MarkdownAnnotator.java:71)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator$1.initialValue(MarkdownAnnotator.java:69)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
        at java.lang.ThreadLocal.get(ThreadLocal.java:150)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator.doAnnotate(MarkdownAnnotator.java:108)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator.doAnnotate(MarkdownAnnotator.java:53)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:186)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$400(ExternalToolPass.java:43)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:122)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
    Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.AbstractInsnNode PluginClassLoader[net.nicoulaj.idea.markdown, 0.9.7]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 39 more



    java.lang.NoClassDefFoundError: org/objectweb/asm/tree/AbstractInsnNode
        at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:35)
        at org.parboiled.Parboiled.createParser(Parboiled.java:54)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
        at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator$1.initialValue(MarkdownAnnotator.java:71)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator$1.initialValue(MarkdownAnnotator.java:69)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:160)
        at java.lang.ThreadLocal.get(ThreadLocal.java:150)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator.doAnnotate(MarkdownAnnotator.java:108)
        at net.nicoulaj.idea.markdown.annotator.MarkdownAnnotator.doAnnotate(MarkdownAnnotator.java:53)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.c(ExternalToolPass.java:186)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$400(ExternalToolPass.java:43)
        at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:122)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
        at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
        at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
        at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
        at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
        at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
        at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
        at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
        at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
        at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
        at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
    Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.AbstractInsnNode PluginClassLoader[net.nicoulaj.idea.markdown, 0.9.7]
        at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 39 more

**Comment by grbspltt** [comment]
Uninstall the plugin then reinstall. Worked for me.

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
