### ISSUE TITLE
another error

### ISSUE THREAD

**Issue by deadmann** [nicoulaj/idea-markdown#239]
just to tell...
and when i alt+Enter, the menu won't come up and error repeat

Language Language: Markdown doesn't participate in view provider Injected file 'directives.js' : [Language: Markdown]
java.lang.AssertionError: Language Language: Markdown doesn't participate in view provider Injected file 'directives.js' : [Language: Markdown]
	at com.intellij.extapi.psi.PsiFileBase.a(PsiFileBase.java:58)
	at com.intellij.extapi.psi.PsiFileBase.<init>(PsiFileBase.java:40)
	at net.nicoulaj.idea.markdown.lang.psi.impl.MarkdownFileImpl.<init>(MarkdownFileImpl.java:52)
	at net.nicoulaj.idea.markdown.lang.parser.MarkdownParserDefinition.createFile(MarkdownParserDefinition.java:132)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:222)
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.registerInjection(InjectorUtils.java:112)
	at org.intellij.plugins.intelliLang.inject.TemporaryPlacesInjector.getLanguagesToInject(TemporaryPlacesInjector.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:443)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:315)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:193)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:188)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

java.lang.AssertionError: Language Language: Markdown doesn't participate in view provider Injected file 'directives.js' : [Language: Markdown]
	at com.intellij.extapi.psi.PsiFileBase.a(PsiFileBase.java:58)
	at com.intellij.extapi.psi.PsiFileBase.<init>(PsiFileBase.java:40)
	at net.nicoulaj.idea.markdown.lang.psi.impl.MarkdownFileImpl.<init>(MarkdownFileImpl.java:52)
	at net.nicoulaj.idea.markdown.lang.parser.MarkdownParserDefinition.createFile(MarkdownParserDefinition.java:132)
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.doneInjecting(MultiHostRegistrarImpl.java:222)
	at org.intellij.plugins.intelliLang.inject.InjectorUtils.registerInjection(InjectorUtils.java:112)
	at org.intellij.plugins.intelliLang.inject.TemporaryPlacesInjector.getLanguagesToInject(TemporaryPlacesInjector.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:443)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:315)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:144)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:193)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass$2.process(InjectedGeneralHighlightingPass.java:188)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by nicoulaj** [comment]
**Notice**: This plugin is no more maintained and it has been removed from Jetbrains plugins repository. [There is a Markdown plugin officially supported by Jetbrains](https://plugins.jetbrains.com/plugin/7793).
